"""lawfactoapi URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from lawfactoapi.lawfactoapi import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^ncdrc_casehistory/$',
        views.NcdrcCaseHistoryAPIView.as_view(),
        name='ncdrc_casehistory'),
    url(r'^statecommissiondelhi_casehistory/$',
        views.StateCommissionDelhiCaseHistoryAPIView.as_view(),
        name='statecommissiondelhi_casehistory'),
    url(r'^centraldelhi_casehistory/$',
        views.CentralDelhiCaseHistoryAPIView.as_view(),
        name='centraldelhi_casehistory'),
    url(r'^eastdelhi_casehistory/$',
        views.EastDelhiCaseHistoryAPIView.as_view(),
        name='eastdelhi_casehistory'),
    url(r'^newdelhi_casehistory/$',
        views.NewDelhiCaseHistoryAPIView.as_view(),
        name='newdelhi_casehistory'),
    url(r'^north_casehistory/$',
        views.NorthCaseHistoryAPIView.as_view(),
        name='north_casehistory'),
    url(r'^northeast_casehistory/$',
        views.NorthEastCaseHistoryAPIView.as_view(),
        name='northeast_casehistory'),
    url(r'^northwest_casehistory/$',
        views.NorthWestCaseHistoryAPIView.as_view(),
        name='northwest_casehistory'),
    url(r'^southdelhi_casehistory/$',
        views.SouthDelhiCaseHistoryAPIView.as_view(),
        name='southdelhi_casehistory'),
    url(r'^south2_casehistory/$',
        views.South2CaseHistoryAPIView.as_view(),
        name='south2_casehistory'),
    url(r'^southwest_casehistory/$',
        views.SouthWestCaseHistoryAPIView.as_view(),
        name='southwest_casehistory'),
    url(r'^westdelhi_casehistory/$',
        views.WestDelhiCaseHistoryAPIView.as_view(),
        name='westdelhi_casehistory'),
    url(r'^ncdrc_casestatus/$',
        views.NcdrcCaseStatusAPIView.as_view(),
        name='ncdrc_casestatus'),
    url(r'^delhistatecommission_casestatus/$',
        views.DelhiStateCommissionCaseStatusAPIView.as_view(),
        name='delhistatecommission_casestatus'),
    url(r'^districteastdelhi_casestatus/$',
        views.DistrictEastDelhiCaseStatusAPIView.as_view(),
        name='districteastdelhi_casestatus'),
    url(r'^districtsouthdelhi_casestatus/$',
        views.DistrictSouthDelhiCaseStatusAPIView.as_view(),
        name='districtsouthdelhi_casestatus'),
    url(r'^districtwestdelhi_casestatus/$',
        views.DistrictWestDelhiCaseStatusAPIView.as_view(),
        name='districtwestdelhi_casestatus'),
    url(r'^districtcentraldelhi_casestatus/$',
        views.DistrictCentralDelhiCaseStatusAPIView.as_view(),
        name='districtcentraldelhi_casestatus'),
    url(r'^districtnewdelhi_casestatus/$',
        views.DistrictNewDelhiCaseStatusAPIView.as_view(),
        name='districtnewdelhi_casestatus'),
    url(r'^districtnortheastdelhi_casestatus/$',
        views.DistrictNorthEastDelhiCaseStatusAPIView.as_view(),
        name='districtnortheastdelhi_casestatus'),
    url(r'^districtnorthwestdelhi_casestatus/$',
        views.DistrictNorthWestDelhiCaseStatusAPIView.as_view(),
        name='districtnorthwestdelhi_casestatus'),
    url(r'^districtsouth2_casestatus/$',
        views.DistrictSouth2CaseStatusAPIView.as_view(),
        name='districtsouth2_casestatus'),
    url(r'^districtsouthwest_casestatus/$',
        views.DistrictSouthWestCaseStatusAPIView.as_view(),
        name='districtsouthwest_casestatus'),
    url(r'^districtnorth_casestatus/$',
        views.DistrictNorthCaseStatusAPIView.as_view(),
        name='districtnorth_casestatus'),
    url(r'^ncdrc_judgment/$',
        views.NcdrcCaseJudgmentAPIView.as_view(),
        name='ncdrc_judgment'),
    url(r'^delhistatecommission_judgment/$',
        views.DelhiStateCommissionJudgmentAPIView.as_view(),
        name='delhistatecommission_judgment'),
    url(r'^districteastdelhi_judgment/$',
        views.DistrictEastDelhiJudgmentAPIView.as_view(),
        name='districteastdelhi_judgment'),
    url(r'^districtsouthdelhi_judgment/$',
        views.DistrictSouthDelhiJudgmentAPIView.as_view(),
        name='districtsouthdelhi_judgment'),
    url(r'^districtwestdelhi_judgment/$',
        views.DistrictWestDelhiJudgmentAPIView.as_view(),
        name='districtwestdelhi_judgment'),
    url(r'^districtnortheastdelhi_judgment/$',
        views.DistrictNorthEastDelhiJudgmentAPIView.as_view(),
        name='districtnortheastdelhi_judgment'),
    url(r'^districtnorthwestdelhi_judgment/$',
        views.DistrictNorthWestDelhiJudgmentAPIView.as_view(),
        name='districtnorthwestdelhi_judgment'),
    url(r'^districtsouth2_judgment/$',
        views.DistrictSouth2JudgmentAPIView.as_view(),
        name='districtsouth2_judgment'),
    url(r'^districtsouthwest_judgment/$',
        views.DistrictSouthWestJudgmentAPIView.as_view(),
        name='districtsouthwest_judgment'),
    url(r'^districtnorth_judgment/$',
        views.DistrictNorthJudgmentAPIView.as_view(),
        name='districtnorth_judgment'),
    url(r'^ncdrc_order/$',
        views.NcdrcOrderAPIView.as_view(),
        name='ncdrc_order'),
    url(r'^statecommision_order/$',
        views.StateCommisionOrderAPIView.as_view(),
        name='statecommision_order'),
    url(r'^eastdelhi_order/$',
        views.EastDelhiOrderAPIView.as_view(),
        name='eastdelhi_order'),
    url(r'^westdelhi_order/$',
        views.EastDelhiOrderAPIView.as_view(),
        name='westdelhi_order'),
    url(r'^centraldelhi_order/$',
        views.CentralDelhiOrderAPIView.as_view(),
        name='centraldelhi_order'),
    url(r'^northeastdelhi_order/$',
        views.NorthEastDelhiOrderAPIView.as_view(),
        name='northeastdelhi_order'),
    url(r'^northwestdelhi_order/$',
        views.NorthWestDelhiOrderAPIView.as_view(),
        name='northwestdelhi_order'),
    url(r'^south2_order/$',
        views.South2OrderAPIView.as_view(),
        name='south2_order'),
    url(r'^southwest_order/$',
        views.SouthWestOrderAPIView.as_view(),
        name='southwest_order'),
    url(r'^north_order/$',
        views.NorthOrderAPIView.as_view(),
        name='north_order'),
    url(r'^cgatnew_casestatus/$',
        views.CgatNewCaseStatus.as_view(),
        name='cgatnew_casestatus'),
    url(r'^cgatnew_caseorder/$',
        views.CgatNewCaseOrder.as_view(),
        name='cgatnew_caseorder'),
    url(r'^cgatnew_casejudgment/$',
        views.CgatNewCaseJudgment.as_view(),
        name='cgatnew_casejudgment'),
]

